<a href="https://colab.research.google.com/github/aman-5137/half_plasma/blob/main/_5_DataCleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [64]:
import pandas as pd

df = pd.read_csv("/content/sample_data/loan_data.csv")
df

,applicant_id,name,age,income,credit_score,loan_amount,employment_status,married,gender,approved
0,APP1170,Raj Smith,NaN,"$66,400",NaN,89100.0,Unemployed,No,Female,Rejected
1,APP1177,Omar Silva,25.0,"$75,700",645.0,228600.0,Employed,NaN,Male,Approved
2,APP1132,Mei Khan,24.0,"$26,400",580.0,5000.0,employed,Yes,Female,Approved
3,APP1193,Liam Ali,28.0,"$78,500",NaN,272600.0,Employed,No,Female,Approved
4,APP1102,Raj Kumar,35.0,NaN,573.0,159000.0,employed,N,Female,Rejected
...,...,...,...,...,...,...,...,...,...,...
207,APP1112,Nina Silva,39.0,"$62,500",834.0,159800.0,Employed,Yes,Female,Approved
208,APP1184,Eva Smith,54.0,"$103,000",818.0,89900.0,employed,No,male,Approved
209,APP1131,Omar Khan,55.0,"$64,600",688.0,47600.0,NaN,Yes,M,Approved
210,APP1152,Nina Lee,30.0,"$40,500",669.0,290300.0,Self Employed,No,Female,Rejected
211,APP1106,Eva Patel,-5.0,"$61,200",505.0,251200.0,employed,Yes,male,Rejected

In [65]:
df.info() # This will tell us the column information

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 212 entries, 0 to 211
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   applicant_id       212 non-null    object
 1   name               212 non-null    object
 2   age                194 non-null    float64
 3   income             202 non-null    object
 4   credit_score       195 non-null    float64
 5   loan_amount        212 non-null    float64
 6   employment_status  201 non-null    object
 7   married            200 non-null    object
 8   gender             202 non-null    object
 9   approved           212 non-null    object
dtypes: float64(3), object(7)
memory usage: 16.7+ KB

In [66]:
df.describe() # It will give us the count, min, max, mean, etc.

              age  credit_score    loan_amount
count  194.000000    195.000000     212.000000
mean    43.448454    648.574359  152261.792453
std     20.945523    132.753971   85665.271670
min     -5.000000      0.000000    5000.000000
25%     31.000000    582.500000   88950.000000
50%     41.000000    652.000000  155800.000000
75%     54.000000    737.500000  207575.000000
max    200.000000    850.000000  448800.000000

In [67]:
df.isna().sum() # This will tell us which column has how many NA (where values are not available)

applicant_id          0
name                  0
age                  18
income               10
credit_score         17
loan_amount           0
employment_status    11
married              12
gender               10
approved              0
dtype: int64

In [68]:
df.shape # This gives us the size of the file containing data

(212, 10)

In [69]:
df

,applicant_id,name,age,income,credit_score,loan_amount,employment_status,married,gender,approved
0,APP1170,Raj Smith,NaN,"$66,400",NaN,89100.0,Unemployed,No,Female,Rejected
1,APP1177,Omar Silva,25.0,"$75,700",645.0,228600.0,Employed,NaN,Male,Approved
2,APP1132,Mei Khan,24.0,"$26,400",580.0,5000.0,employed,Yes,Female,Approved
3,APP1193,Liam Ali,28.0,"$78,500",NaN,272600.0,Employed,No,Female,Approved
4,APP1102,Raj Kumar,35.0,NaN,573.0,159000.0,employed,N,Female,Rejected
...,...,...,...,...,...,...,...,...,...,...
207,APP1112,Nina Silva,39.0,"$62,500",834.0,159800.0,Employed,Yes,Female,Approved
208,APP1184,Eva Smith,54.0,"$103,000",818.0,89900.0,employed,No,male,Approved
209,APP1131,Omar Khan,55.0,"$64,600",688.0,47600.0,NaN,Yes,M,Approved
210,APP1152,Nina Lee,30.0,"$40,500",669.0,290300.0,Self Employed,No,Female,Rejected
211,APP1106,Eva Patel,-5.0,"$61,200",505.0,251200.0,employed,Yes,male,Rejected

In [70]:
# To find duplicate rows
duplicate_rows = df[df.duplicated(keep = False)]
print(duplicate_rows)

    applicant_id        name   age   income  credit_score  loan_amount  \
3        APP1193    Liam Ali  28.0  $78,500           NaN     272600.0
5        APP1182   Raj Silva  26.0  $12,000         574.0      78000.0
13       APP1199  Omar Smith  47.0  $56,600         627.0     249000.0
16       APP1029   Mei Silva  60.0  $57,700         806.0     117600.0
30       APP1012  Sara Patel  55.0  $47,600         632.0     113300.0
38       APP1115   Diya Khan   NaN  $61,300         745.0      70700.0
60       APP1035     Mei Lee  36.0    34100         647.0     277800.0
64       APP1115   Diya Khan   NaN  $61,300         745.0      70700.0
69       APP1054   Sara Khan  50.0  $26,300         624.0     129000.0
73       APP1193    Liam Ali  28.0  $78,500           NaN     272600.0
94       APP1092    Eva Chen   NaN  $12,000         786.0     126300.0
106      APP1035     Mei Lee  36.0    34100         647.0     277800.0
118      APP1112  Nina Silva  39.0  $62,500         834.0     159800.0
119      APP1010  Sara Smith  37.0  $46,400         760.0     140900.0
129      APP1029   Mei Silva  60.0  $57,700         806.0     117600.0
134      APP1085   Diya Chen  42.0  $55,400         582.0     218600.0
154      APP1085   Diya Chen  42.0  $55,400         582.0     218600.0
160      APP1010  Sara Smith  37.0  $46,400         760.0     140900.0
161      APP1054   Sara Khan  50.0  $26,300         624.0     129000.0
165      APP1199  Omar Smith  47.0  $56,600         627.0     249000.0
176      APP1012  Sara Patel  55.0  $47,600         632.0     113300.0
177      APP1092    Eva Chen   NaN  $12,000         786.0     126300.0
203      APP1182   Raj Silva  26.0  $12,000         574.0      78000.0
207      APP1112  Nina Silva  39.0  $62,500         834.0     159800.0

    employment_status married  gender  approved
3            Employed      No  Female  Approved
5          Unemployed       Y    Male  Rejected
13           employed      no       M  Approved
16      self employed     NaN    Male  Approved
30           employed     Yes  Female  Rejected
38      Self-Employed     yes    male  Approved
60           employed      No       M  Rejected
64      Self-Employed     yes    male  Approved
69      Self Employed     Yes       F  Rejected
73           Employed      No  Female  Approved
94           employed      no    Male  Rejected
106          employed      No       M  Rejected
118          Employed     Yes  Female  Approved
119          employed       N    Male  Approved
129     self employed     NaN    Male  Approved
134               NaN     NaN    Male  Rejected
154               NaN     NaN    Male  Rejected
160          employed       N    Male  Approved
161     Self Employed     Yes       F  Rejected
165          employed      no       M  Approved
176          employed     Yes  Female  Rejected
177          employed      no    Male  Rejected
203        Unemployed       Y    Male  Rejected
207          Employed     Yes  Female  Approved

In [71]:
before_duplicates_removed = df.shape[0]
df = df.drop_duplicates()
after_duplicates_removed = df.shape[0]

print("Before removing duplicates: ", before_duplicates_removed)
print("After removing duplicates: ", after_duplicates_removed)

Before removing duplicates:  212
After removing duplicates:  200

In [72]:
# We do not need unnecessary columns during a model training so we will remove them too
df = df.drop(columns=['applicant_id', 'name'])

In [73]:
# Clean the 'income' column by removing '$' and ',' characters and converting to numeric
df['income'] = df['income'].astype(str).str.replace(r'[$ ,]', '', regex=True)
df['income'] = pd.to_numeric(df['income'], errors='coerce')

In [74]:
df.head()

,age,income,credit_score,loan_amount,employment_status,married,gender,approved
0,NaN,66400.0,NaN,89100.0,Unemployed,No,Female,Rejected
1,25.0,75700.0,645.0,228600.0,Employed,NaN,Male,Approved
2,24.0,26400.0,580.0,5000.0,employed,Yes,Female,Approved
3,28.0,78500.0,NaN,272600.0,Employed,No,Female,Approved
4,35.0,NaN,573.0,159000.0,employed,N,Female,Rejected

In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 200 entries, 0 to 211
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   age                184 non-null    float64
 1   income             188 non-null    float64
 2   credit_score       184 non-null    float64
 3   loan_amount        200 non-null    float64
 4   employment_status  190 non-null    object
 5   married            190 non-null    object
 6   gender             190 non-null    object
 7   approved           200 non-null    object
dtypes: float64(4), object(4)
memory usage: 14.1+ KB

In [76]:
df.gender.value_counts()

gender
Male      37
M         34
female    34
male      31
F         28
Female    26
Name: count, dtype: int64

In [77]:
df['gender'] = df['gender'].map({"male":"Male", 'm': "Male", "female": "Female", "f" : "Female"})

In [78]:
df.gender.value_counts()

gender
Female    34
Male      31
Name: count, dtype: int64

In [79]:
df.married.value_counts()

married
Yes    54
No     34
Y      33
yes    27
N      24
no     18
Name: count, dtype: int64

In [80]:
df['married'] = df['married'].map({'yes':'Yes', 'no':'No', 'Y': "Yes", "N": "No"})

In [81]:
df.married.value_counts()

married
Yes    60
No     42
Name: count, dtype: int64

In [82]:
df.employment_status.value_counts()

employment_status
employed         61
Employed         49
Self-Employed    20
Unemployed       17
unemployed       15
self employed    14
Self Employed    14
Name: count, dtype: int64

In [83]:
df['employment_status'] = df['employment_status'].map({"employed":"Employed", "unemployed":"Unemployed", "self employed":"Self-Employed", "Self Employed": "Self-Employed"})

In [84]:
df.describe()

              age         income  credit_score    loan_amount
count  184.000000     188.000000    184.000000     200.000000
mean    43.527174   52789.361702    645.951087  151629.500000
std     21.366674   21143.955119    134.420646   86473.742375
min     -5.000000   12000.000000      0.000000    5000.000000
25%     31.000000   37925.000000    581.500000   88250.000000
50%     41.000000   51150.000000    656.000000  157450.000000
75%     54.000000   68325.000000    729.250000  205700.000000
max    200.000000  104000.000000    850.000000  448800.000000